BBN-Q/QGL

QGL/Compiler.py

A single definition per unique function should be enough

Prevent duplicate definitions of subroutines

---

QGL/Compiler.py
QGL/PulsePrimitives.py
tests/test_APS2Pattern.py
tests/test_APSPattern.py
tests/test_Compiler.py
tests/test_ControlFlow.py

Applies the Z gate to all CR pulses where the qubit is the target

Feature Z-CR target

---

QGL/Compiler.py

The edge may be in the connectivity graph, but never used in the pulse
sequence
--DR

Check if the shifted pulse is part of the seq.

---

QGL/Compiler.py

`hashshape()` only refers to the pulse shape, not amplitude or phase. The
sum of pulses with different amplitudes or phases produces a different
pulse shape, so it needs a new hash.

The sum of pulses differs with their amp or phase

---

QGL/drivers/APS2Pattern.py

This is only a limited fix, but it is necessary to set the mod. frequency at start of the sequence, after the subroutines are defined. 
--DR

Modulation with subroutines

---

QGL/Channels.py
QGL/Compiler.py
QGL/PatternUtils.py

To support QGL2 multi-qbit programs, add a flag to control whether to add a slave trigger.
For normal operations, no change. If you supply the qgl2 flag to `compile_to_hardware`, then you get no added slave trigger, unless you also add the new `addQGL2SlaveTrigger` flag. The result is that we only create the slave trigger for the program (single sequence) whose AWG is that of the slave trigger.
Also clean up log messages, and add an error check in 1 `PatternUtils` class.

QGL2 multiqbit support: Allow selective adding slave trigger

---

QGL/PulseSequencePlotter.py
QGL/drivers/APS2Pattern.py
QGL/drivers/APSPattern.py
QGL/drivers/TekPattern.py

Decouples ChannelLibrary setup from sequence file names, which is especially
handy when debuging test vectors. To get this to work, we need to handle the
fact that the APS1 and APS2 both use an h5 file extension. So, this also adds an
`is_compatible_file(filename)` method which drivers must define.

Choose translator from file extension.

---

QGL/BasicSequences/Feedback.py
QGL/BasicSequences/RB.py
QGL/BasicSequences/Rabi.py
QGL/BasicSequences/helpers.py
QGL/PulsePrimitives.py
QGL/Tomography.py
tests/test_QGL.py
tests/test_data/multi-operators.h5

After this, `MEAS` may only be called with a single positional argument. To get simultaneous measurement, you now need to write `MEAS(q1)*MEAS(q2)`, for example. The tuple input version for joint measurement has been removed.

Simplify definition of MEAS, revise default CNOT to use an Edge

---

QGL/PulsePrimitives.py
QGL/PulseSequencer.py

Using the "algorithm" that @caryan and I came up with yesterday.
This solution is not universal, but it should work so long as `Pulse.label` is a valid pulse primitive name. Even within that domain there are some edge cases I am not handling, for instance `Ztheta` pulses will appear as `Ztheta(q1, frameChange=0.212)` even though the actual name of the keyword argument is `angle` and not `frameChange`. Also, autodyne `MEAS` pulses will appear with `MEAS(q1, amp=0.5, phase=0.0, shapeFun=<...autodyne...>)`. The `amp` and `phase` printing I can fix after we merge #46. I simply need to build `ignoredStrParams` based upon whether `amp` and `phase` are passed as kwargs. The `shapeFun` piece breaks my lookup algorithm because we swap `shapeFun` and `baseShape`, and `baseShape` is not in the …

Make str(Pulse) return enough information to reconstruct the object

---

QGL/Compiler.py

Most of the work was in getting `str(Pulse)` to behave. Consequently, we can just use ipython's pretty printer to get reasonable output. I've put this behind an `if not qgl2` guard under the assumption that if you are using QGL2, you already have the code somewhere.
Fixes #43.

Save input code to file.

---

QGL/Channels.py
QGL/Compiler.py
QGL/PulsePrimitives.py
QGL/PulseSequencer.py
QGL/PulseShapes.py

The names `square` or `constant` make assumptions about what is before or after and having a single pulse shape for "constant" pulses simplifies some TimeAmp checks. Leaving an alias from `square` -> `constant` should silently update ChannelParams files.

remove square pulse in favour of constant

---

QGL/PulseSequencer.py

Apparently this line is still necessary, even with namedtuples.
This fixes
`state_tomo([X(q1)*X(q2), qubits=(q1,)])`
with q2 in a slave APS. Otherwise the slave trigger tries to get attached to the ''same'' pulse block for every segment

Copy PulseBlock one layer deeper

---

QGL/BasicSequences/CR.py
QGL/BasicSequences/Decoupling.py
QGL/BasicSequences/Rabi.py
QGL/BasicSequences/T1T2.py
QGL/BasicSequences/helpers.py
QGL/Compiler.py

First steps toward #44. The idea is to make the `axis_descriptor` passable as a keyword argument, so that time-domain sequences like Ramsey, T1, etc. can pass along axis information.

Add basic meta program output

---

QGL/PulsePrimitives.py

With pulse memoization turned on be sure to clear the pulse cache and recreate pulses before updating. I've added a helper `PulsePrimitives.clear_pulse_cache` to make it easier to dig out.
e.g.
```python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
Type "copyright", "credits" or "license" for more information.
IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
In [1]: from QGL import *
In [2]: q1 = QubitFactory("q1")
In [3]: pulse_lib = [AC(q1, ct) for ct in range(24)]
In [4]: seqs = [[pulse_lib[np.random.randint(24)] for _ in range(10)]]
In [5]: from QGL.drivers …
```

fix AC in-place waveform update

---

.gitignore
QGL/Compiler.py
QGL/PulsePrimitives.py
QGL/drivers/APS2Pattern.py
tests/test_Compiler.py
tests/test_Sequences.py
tests/test_data/awg/TestAPS2/CNOT_CR_mux/CNOT_CR_mux-APS1.h5
tests/test_data/awg/TestAPS2/CNOT_CR_mux/CNOT_CR_mux-APS3.h5
tests/test_data/awg/TestAPS2/CNOT_CR_mux/CNOT_CR_mux-APS5.h5

Switches to 2nd NCO when modulation frequency is different from the previous pulse.
For example, to switch between qubit and CR drive on the same APS.
Only working for max 2 frequencies.

Enable 2nd NCO

---

QGL/BasicSequences/__init__.py
QGL/BasicSequences/helpers.py
QGL/PulseShapes.py

Two-step cavity reset pulse. Used by https://github.com/BBN-Q/Qlab/pull/91
The CLEAR pulse shape has additional parameters: `step_length`, `amp1`, `amp2` for the length of each of the two reset steps, and their relative amplitudes.

Cavity reset pulse

---

QGL/Compiler.py
tests/test_Compiler.py

Fixes issue #82.
Counts the number of measurements per "wire" and takes the max over the wires
for each sequence. Eventually we'd like to skip the `max` reduction and keep the
individual wire values.

Improve measurement counting algorithm.

---

QGL/ChannelLibrary.py
QGL/Channels.py
QGL/Compiler.py
tests/test_Compiler.py
tests/test_Sequences.py

Allows one to make the measurement -> digitizer connection explicit. This allows things like counting the number of measurements for each digitizer/receiver, such that these do not have to be uniform.

Add ReceiverChannels

---

QGL/Compiler.py

Fix frame-update propagation for CR gates, analogously to single-qubit gates in https://github.com/BBN-Q/QGL/pull/74/commits/7d4b0b9ffc5b9b3f4742b1512b1043ad4fe811da

Propagate frame change to first non-TA pulse

---

QGL/Channels.py
QGL/Compiler.py
QGL/ControlFlow.py
QGL/PatternUtils.py
tests/test_ControlFlow.py
tests/test_QGL.py
tests/test_data/multi-align.h5
tests/test_data/multi-composite.h5
tests/test_data/multi-operators.h5
tests/test_data/single-ramsey.h5
tests/test_data/single-repeat.h5

And use the passed `channels` to determine where it should broadcast. The specific use case I have in mind is `Wait(q1)`, `Wait(q2)`, etc.
Also introduces a `Store` instruction that I intend to be ignored from the compiler's perspective. But, it is nice for the human.

Allow ControlInstructions to take a channels argument

---

QGL/BasicSequences/CR.py
QGL/BlockLabel.py
QGL/Compiler.py
QGL/ControlFlow.py
QGL/PatternUtils.py
QGL/PulsePrimitives.py
QGL/PulseSequencer.py
QGL/Scheduler.py
QGL/__init__.py
tests/helpers.py
tests/test_Compiler.py
tests/test_Scheduler.py
tests/test_Sequences.py
tests/test_pulse_types.py

Adds a scheduler to tightly pack a serial QGL1 sequence into a parallelized sequence. The user add explicit `Barrier()`s to indicate time boundaries that the scheduler should not cross.
In the process of developing this, I ran into a fairly fundamental limitation of the current QGL implementation in that it does not support operations such as:
```python
CNOT(q1,q2) * CNOT(q3, q4)
```
At least for the `CNOT_CR` implementation we return a list of pulses, and python doesn't define multiplication between lists. Consequently, this PR also introduces a new `CompoundGate` type to the pulse hierarchy which is a thin wrapper around python lists, but which allows us to define `*` on the `CompoundGate` type. This PR introduces use of `CompoundGate`s for `echoCR`, `ZX_90`, and `CNOT_CR`. A nice …

Scheduler and CompoundGates

---

QGL/PulsePrimitives.py

Seems to better match user expectations about what these primitives do.
The angle -> amplitude conversion is done in a lookup table constructed inside
Utheta. This allows usage like:
Xtheta(q1, angle=pi/4)
The user can force the choice of a particular pulse amplitude by providing the
'amp' keyword argument. e.g.
Xtheta(q1, amp=0.1)
will stuff function like it used to. This preserved backwards compatibility with
existing code.

Utheta, Ytheta, and Ztheta operate on rotation angles rather than amplitudes.

---

QGL/BasicSequences/Feedback.py
QGL/ControlFlow.py

Workaround to specify all the multi-qubit branches even when only a
subset is measured and reset

Reset a register subset

---

QGL/ChannelLibrary.py
QGL/Channels.py
QGL/PulsePrimitives.py
QGL/__init__.py

Possible fix to #121 
Adds a new trigger pulse type for adding markers on the digital outputs, along with a MarkerFactory and a way to specify what channels are involved in the YAML.
In the YAML you can now do:
```yaml
qubits:
#qubit definitions
markers:
my_trigger: BBNAPS1 12m1
```
And then in your QGL code do:
``` python
my_trigger_chan = MarkerFactory("my_trigger")
seq = [[X90(q), MEAS(q) * TRIG(my_trigger_chan)]]
```
Thoughts?

Add marker factory for unattached markers.

---

QGL/PulseSequencePlotter.py

in order to satisfy newer bokeh versions (roughly > 0.12.8). @dieris could you test this out for me?
I think the newer bokeh versions are actually using binary transport instead of JSON to go from python->JS, so things appear snappier.

Remove slider for plot_pulse_files for sequences of unit length

---

QGL/ChannelLibraries.py

Without slave trigger. To be used for TDM trigger: Internal and all the
slave APS trigger: SYSTEM. This also allows the master to run last [here](https://github.com/BBN-Q/Auspex/blob/b7442bcb1e5c28800d27a8838ad03bb3eaaa5965/src/auspex/exp_factory.py#L68-L73)

Allow TDM to be the master

---

QGL/PulsePrimitives.py

Allow sequences with MEAS where we are not interested in the measurement
result (e.g. to test QNDness)

Optional choice of dig_trig (or None)

---

doc/QGL-demo.ipynb
doc/config/filters.yml
doc/config/instruments.yml
doc/config/measure.yml

The QGL-demo will not run without a set of config files. 
This PR adds a minimal set of configs in `doc/config` which will allow the demo to run. The config files are not meant to document the config file format but rather allow someone to run the demo out of the box.
The python notebook has also been modified to point directly to these config files.

Adds a minimal config for QGL-demo

---

QGL/Compiler.py
QGL/PatternUtils.py
QGL/PulsePrimitives.py
QGL/PulseSequencer.py
QGL/__init__.py
tests/test_Compiler.py
tests/test_QGL.py

Alternative solution to the issue presented in https://github.com/BBN-Q/QGL/pull/92. This allows to specify any alignment between pulses using `align(mode, pulse1, pulse2)`. `mode` can be either 'left', 'center' (default), or 'right'. `pulse1` and `pulse2` can be any combination of `Pulse`, `PulseBlock`, `CompositePulse`. The alignment of `CompoundGates` is currently not supported (limited workaround for triggers). 
Note: this does not solve https://github.com/BBN-Q/QGL/issues/148, but it's a step towards more flexibility. 
Thoughts?

Align pulses instead of blocks

---

QGL/ChannelLibraries.py

Optionally declare the digitizer triggers in the markers section of the yaml configuration. 
For instance:
```
q1:
measure:
AWG: APSII1 12
trigger: digitizerTrig
...
```
```
markers:
digitizerTrig: APSII1 12m1
```
Alternatively, writing directly `trigger: APSII1 12m1` is still valid.

Define digitizer triggers as markers

---

QGL/Cliffords.py

Some of the 2-q Cliffords were still implemented with the CNOT gates as pulse lists, instead of the current implementation as [CompoundGates](https://github.com/BBN-Q/QGL/pull/103)

Update 2q Cliffords to CompoundGates

---

QGL/Compiler.py
QGL/PatternUtils.py

If the digitizer trigger is disabled: MEAS(dig_trig = None),
the number of measurements for that receiver could be 0. In this case, we now remove the receiver entry entirely

Remove receivers with 0 measurements

---

QGL/BasicSequences/helpers.py

Allow cal descriptor for arbitrary state preparation e.g. using |2>

More generic cal_descriptor

---

QGL/ControlFlow.py
tests/test_ControlFlow.py

this will usually detect when someone is calling qwait the old way,
and raise an error that will require correction

if the "kind" is unknown, raise an exception

---

QGL/ChannelLibraries.py

I'm not sure if they were intentionally left out. Main reasons to add them:
1) Save to database
2) Establish a relation with a source for paramp bias (DC sources) or LO (spec. analyzers)

DC sources and spec. analyzers in database

---

QGL/ChannelLibraries.py

For consistency with https://github.com/BBN-Q/libx6/blob/master/doc/01_Usage.md, I'd rather label first physical, then dsp channel

Revert to old stream labels

---

QGL/BasicSequences/StarkShift.py
QGL/BasicSequences/__init__.py

New sequence creation functions:
- Stark shift spectroscopy.
- Photon number dephasing with cavity displacement + Hahn echo.
- Cavity pump-probe experiments.
Tested using the `sqlalchemy` branch.

Add sequences for Stark Shift-type experiments

---

QGL/GSTTools.py

DiAC Clifford library uses the Atomic one.

Fixed Atomic and DiAtomic Clifford typo.

---

QGL/ChannelLibraries.py
QGL/config.py

DSP content no longer the purview of the channel library. QGL only needs to know which physical receiver channel is being used.

Fixes for adding stream selectors back in

---

QGL/BasicSequences/Feedback.py

consistent with rest of the instructions

Fix mv syntax

---

QGL/GSTTools.py

Update `GSTTools` for pyGSTi 0.9.8 compatibility.
Replace `GateString` objects with `Circuit` objects. Test on hardware for 1 qubit GST.

pyGSTi v0.9.8 compatbility

---

QGL/ChannelLibraries.py
QGL/drivers/APS2Pattern.py

See https://github.com/BBN-Q/QGL/pull/204

TDM input channels
