QGL/PulseSequencer.py

cc @caryan 
This version works on Python 3, but now fails in python 2. The simple test case is:
```
from QGL import *
q1 = QubitFactory(q1)
q2 = QubitFactory(q2)
X(q1)*Y(q2)
```

A start at trying to fix the __repr__ method for PulseBlocks.

---

QGL/BasicSequences/Feedback.py

Improvements to reset function

---

QGL/PulsePrimitives.py

Meas + decoupling pi pulse on the other qubits
See https://github.com/BBN-Q/PyQLab/pull/102

MeasEcho pulse

---

QGL/Channels.py

Check if channel property is already string

---

QGL/Plotting.py
QGL/PulseSequencePlotter.py

Plotting slider now works in static files as well!

Fix bokeh plotting

---

README.md

JSONLibraryMigrator has moved

---

QGL/PulseSequencePlotter.py
QGL/drivers/APS2Pattern.py
QGL/drivers/APSPattern.py
tests/test_Sequences.py

Read sequence file functions now return lists of time amplitude pairs.  Plots are closer to hardware (i.e. no interpolation) and helpful for performance for plots with lots of time amplitude pairs.

Sparse plots

---

QGL/BasicSequences/CR.py
QGL/BasicSequences/__init__.py

To be used for fine tuning of CR pulse amp., see https://github.com/BBN-Q/Qlab/pull/63

Seq for CR ampl. calibration

---

QGL/drivers/APS2Pattern.py

If there is only one subroutine, it's the last set of instructions

Support single subroutine

---

QGL/PulseSequencePlotter.py

Walk drivers package to find translators

---

QGL/Compiler.py
QGL/PulseSequencer.py

Examines the shapeFun for the special "square" and "constant" pulse shapes.
Alternate solution for BBN-Q/PyQLab#85.

Set isTimeAmp in Pulse constructor.

---

QGL/BasicSequences/CR.py

the amp. input was not passed down to echoCR

Pass amp. value in len/phase CR cal.

---

QGL/Compiler.py

Check if attribute exists before reading its value. Response to:
https://github.com/BBN-Q/QGL/commit/7d4b0b9ffc5b9b3f4742b1512b1043ad4fe811da#commitcomment-19377404

Check for isTimeAmp attribute

---

QGL/PatternUtils.py

See https://github.com/BBN-Q/QGL/commit/58a7ab58374d82732da70beda95652553ba7ae09

physChan AWG field is now instrument

---

.travis.yml
QGL/ControlFlow.py
QGL/drivers/APS2Pattern.py
tests/test_ControlFlow.py

Currently ignored by the APS2 translator.

Add an address field to ComparisonInstructions.

---

QGL/BasicSequences/CR.py
QGL/BasicSequences/Decoupling.py
QGL/BasicSequences/Rabi.py
QGL/BasicSequences/T1T2.py
QGL/BasicSequences/__init__.py
QGL/BasicSequences/helpers.py

time -> delay. Fix conflict with https://github.com/BBN-Q/Auspex/issues/73

Rename time descriptor

---

QGL/PulsePrimitives.py

The previous version modified the mutable default argument of [].

Stop appending duplicate values to ignoredStrParams.

---

QGL/Compiler.py
tests/test_Compiler.py

Fix off-by-one error in frame update code.

---

QGL/ChannelLibrary.py

Marker lengths now loaded from instrument yaml

---

tests/test_pulse_types.py

Alternatively, update to new config scheme

Explicitly call CNOT_CR on promotion test

---

setup.py

To be used for https://github.com/BBN-Q/Auspex/pull/186

Load module to install from auspex

---

QGL/PulseSequencePlotter.py

Since we are at it, I suggest to avoid waveforms with the same color!

More color options for >9 waveforms

---

QGL/Plotting.py
QGL/PulseSequencePlotter.py

Local resources for output_file, config issue that blew up plotting, and color range tweak.

Fix some minor bokeh issues

---

QGL/BasicSequences/helpers.py

Cal data could be the only one partition. See https://github.com/BBN-Q/Auspex/pull/220

Allow any partition for cal data

---

QGL/Compiler.py

Optional sequence compiler for TDM. Default = False

Choose compile for tdm

---

README.md
setup.py

I'd like some feedback on version numbers.  Unless people are good with the latest and greatest.

First pass at python deps in setup.py

---

QGL/BasicSequences/CR.py
QGL/PulsePrimitives.py

Following Sheldon et al., PRA 93 (2016)

CR tomography and cancellation pulse

---

QGL/BasicSequences/Rabi.py

Utheta on the correct set of qubits. Fixes bug introduced in https://github.com/BBN-Q/QGL/pull/173

Fix RabiAmp_N

---

QGL/ChannelLibraries.py

Even with the TDM triggering, we need a slave trigger for the APS1s

Allow for slave trigger for APS1

---

QGL/PulseSequencer.py

Fixes https://github.com/BBN-Q/QGL/issues/188

Fix alignment for equal-length pulses

---

QGL/ChannelLibraries.py

Modified set_measure and set_control to be compatible with the hardware configuration of APS1.

Added compatibility for using APS1

---

QGL/ChannelLibraries.py
QGL/Channels.py
QGL/drivers/APS2Pattern.py

Add measurement attribute that refers to the TDM input for the digitized result. Useful to set the correct   read value to `CrossBar`

Add TDM channels

---

requirements.txt
setup.py

Roll back sqlalchemy version to 1.2.15 (from 1.2.17)

---

QGL/BasicSequences/Feedback.py
QGL/TdmInstructions.py

Cherry pick commits from master

Fix TDM instructions

---

QGL/drivers/APS2Pattern.py

Merge in the rest of develop.

---

QGL/ChannelLibraries.py

Write your favorite comments with `cl.save_as(name, notes)`

Optionally save notes to chan. library

---

QGL/drivers/APS2Pattern.py

Read TDM instructions

---

.travis.yml
QGL/ChannelLibraries.py
requirements.txt
setup.py

2019.2 Minor Tweaks

---

QGL/ChannelLibraries.py
QGL/PulseSequencer.py

Fix `isTimeAmp` check to allow for arbitrarily long constant pulses
(+ print cal. log)

Fix constant pulses

---

QGL/ChannelLibraries.py

Print a table comparing differences between channel libraries in a sqlite database. Require [this
](https://github.com/BBN-Q/bbndb/tree/feature/cl-diff) bbndb branch.

Compare two channel libraries

---

QGL/ChannelLibraries.py

trying to clean up branches, this doesnt seem to cause any harm

Generic new_transceiver function for dummy/aps3 noodling

---

QGL/ChannelLibraries.py

In a graph with tables similar to the auspex pipeline

Display qubit and edge properties
